<?php

/**
 * Biblioteca de modelos de fatura gratuitos (Angola / AGT).
 * Ficheiros gerados em public/modelos-fatura/*.html
 */
return [

    'path' => 'modelos-fatura',

    'levels' => [
        'basico' => [
            'label' => 'Básico',
            'description' => 'Layouts limpos para começar a faturar em minutos.',
        ],
        'intermedio' => [
            'label' => 'Intermédio',
            'description' => 'IVA, retenção e vários itens — prontos para PME.',
        ],
        'avancado' => [
            'label' => 'Avançado',
            'description' => 'Campos AGT, séries, QR e uso profissional.',
        ],
    ],

    'categories' => [
        'factura' => 'Factura',
        'factura-recibo' => 'Factura-Recibo',
        'proforma' => 'Factura Proforma',
        'recibo' => 'Recibo',
        'orcamento' => 'Orçamento',
        'nota-credito' => 'Nota de Crédito',
        'nota-debito' => 'Nota de Débito',
    ],

    'templates' => [
        [
            'slug' => 'factura-basica-kwanzas',
            'title' => 'Factura básica em Kwanzas',
            'level' => 'basico',
            'category' => 'factura',
            'style' => 'minimal',
            'description' => 'Modelo simples de factura em Kz para micro e pequenas empresas em Angola.',
            'features' => ['Dados do emitente e cliente', 'Tabela de itens', 'Total em Kz', 'Espaço para NIF'],
        ],
        [
            'slug' => 'factura-recibo-simples',
            'title' => 'Factura-Recibo simples',
            'level' => 'basico',
            'category' => 'factura-recibo',
            'style' => 'minimal',
            'description' => 'Factura-recibo gratuita para pagamento imediato — ideal para prestadores de serviços.',
            'features' => ['Factura e recibo num só documento', 'Campos de pagamento', 'Assinatura'],
        ],
        [
            'slug' => 'proforma-basica',
            'title' => 'Factura proforma básica',
            'level' => 'basico',
            'category' => 'proforma',
            'style' => 'classic',
            'description' => 'Proforma para orçamentar vendas antes da factura definitiva AGT.',
            'features' => ['Marca “PROFORMA”', 'Validade da proposta', 'Totais estimados'],
        ],
        [
            'slug' => 'recibo-pagamento',
            'title' => 'Recibo de pagamento',
            'level' => 'basico',
            'category' => 'recibo',
            'style' => 'minimal',
            'description' => 'Recibo simples para confirmar recebimentos em dinheiro, TPA ou transferência.',
            'features' => ['Valor por extenso', 'Método de pagamento', 'Referência'],
        ],
        [
            'slug' => 'orcamento-simples',
            'title' => 'Orçamento / cotação simples',
            'level' => 'basico',
            'category' => 'orcamento',
            'style' => 'classic',
            'description' => 'Modelo de orçamento para apresentar preços a clientes em Luanda e no país.',
            'features' => ['Lista de serviços', 'Condições', 'Prazo de validade'],
        ],
        [
            'slug' => 'factura-iva-14',
            'title' => 'Factura com IVA 14%',
            'level' => 'intermedio',
            'category' => 'factura',
            'style' => 'classic',
            'description' => 'Factura com cálculo de IVA à taxa geral de 14% (Código do IVA Angola).',
            'features' => ['Coluna IVA', 'Base tributável', 'Total com imposto'],
        ],
        [
            'slug' => 'factura-iva-reduzido',
            'title' => 'Factura com IVA taxa reduzida',
            'level' => 'intermedio',
            'category' => 'factura',
            'style' => 'classic',
            'description' => 'Modelo para bens/serviços com taxa reduzida de IVA em Angola.',
            'features' => ['Taxa configurável', 'Discriminação por linha', 'Resumo de impostos'],
        ],
        [
            'slug' => 'factura-multiplos-itens',
            'title' => 'Factura com múltiplos itens',
            'level' => 'intermedio',
            'category' => 'factura',
            'style' => 'corporate',
            'description' => 'Layout para facturas longas com vários produtos ou serviços.',
            'features' => ['Até 12 linhas de exemplo', 'Subtotais', 'Observações'],
        ],
        [
            'slug' => 'factura-retencao-fonte',
            'title' => 'Factura com retenção na fonte 6,5%',
            'level' => 'intermedio',
            'category' => 'factura',
            'style' => 'corporate',
            'description' => 'Modelo com retenção na fonte sobre serviços — comum em subcontratação em Angola.',
            'features' => ['Linha de retenção 6,5%', 'Valor líquido a receber', 'Nota fiscal'],
        ],
        [
            'slug' => 'factura-recibo-iva',
            'title' => 'Factura-Recibo com IVA',
            'level' => 'intermedio',
            'category' => 'factura-recibo',
            'style' => 'angola',
            'description' => 'Factura-recibo com IVA para negócios que cobram e recebem no acto.',
            'features' => ['IVA + recibo', 'Métodos de pagamento', 'Design Angola'],
        ],
        [
            'slug' => 'factura-servicos-consultoria',
            'title' => 'Factura de serviços / consultoria',
            'level' => 'intermedio',
            'category' => 'factura',
            'style' => 'modern',
            'description' => 'Orientada a consultores, advogados, TI e prestação de serviços profissionais.',
            'features' => ['Descrição detalhada', 'Horas / pacotes', 'Condições de pagamento'],
        ],
        [
            'slug' => 'factura-retalho-loja',
            'title' => 'Factura para loja / retalho',
            'level' => 'intermedio',
            'category' => 'factura',
            'style' => 'modern',
            'description' => 'Modelo para lojas, supermercados e comércio a retalho com códigos de produto.',
            'features' => ['SKU / código', 'Quantidade e preço unitário', 'Desconto por linha'],
        ],
        [
            'slug' => 'factura-com-desconto',
            'title' => 'Factura com desconto comercial',
            'level' => 'intermedio',
            'category' => 'factura',
            'style' => 'classic',
            'description' => 'Inclui desconto percentual e valor líquido antes e depois do IVA.',
            'features' => ['Desconto global', 'Totais claros', 'Notas comerciais'],
        ],
        [
            'slug' => 'nota-credito-basica',
            'title' => 'Nota de crédito',
            'level' => 'intermedio',
            'category' => 'nota-credito',
            'style' => 'classic',
            'description' => 'Nota de crédito para anular ou corrigir facturas emitidas.',
            'features' => ['Referência à factura original', 'Motivo', 'Valores a creditar'],
        ],
        [
            'slug' => 'nota-debito',
            'title' => 'Nota de débito',
            'level' => 'intermedio',
            'category' => 'nota-debito',
            'style' => 'classic',
            'description' => 'Nota de débito para acréscimos após a factura original.',
            'features' => ['Referência documental', 'Motivo do acréscimo', 'Totais'],
        ],
        [
            'slug' => 'factura-agt-avancada',
            'title' => 'Factura avançada pronta para AGT',
            'level' => 'avancado',
            'category' => 'factura',
            'style' => 'angola',
            'description' => 'Campos alinhados à faturação eletrónica AGT: NIF, série, número, datas e IVA.',
            'features' => ['Série e número', 'NIF emitente/cliente', 'Software / hash placeholder', 'QR AGT'],
        ],
        [
            'slug' => 'factura-recibo-agt',
            'title' => 'Factura-Recibo avançada AGT',
            'level' => 'avancado',
            'category' => 'factura-recibo',
            'style' => 'angola',
            'description' => 'Factura-recibo com blocos AGT para PME que usam documento fiscal eletrónico.',
            'features' => ['Tipo de documento', 'Campos AGT', 'Assinaturas', 'QR'],
        ],
        [
            'slug' => 'proforma-importacao',
            'title' => 'Proforma para importação / exportação',
            'level' => 'avancado',
            'category' => 'proforma',
            'style' => 'corporate',
            'description' => 'Proforma internacional com Incoterms, porto e moeda (USD/EUR/Kz).',
            'features' => ['Incoterms', 'Moeda estrangeira', 'Dados de carga'],
        ],
        [
            'slug' => 'factura-restaurante',
            'title' => 'Factura / conta restaurante',
            'level' => 'avancado',
            'category' => 'factura',
            'style' => 'modern',
            'description' => 'Layout para restauração, cafés e hotelaria com taxa de serviço opcional.',
            'features' => ['Mesa / pedido', 'Taxa de serviço', 'IVA'],
        ],
        [
            'slug' => 'factura-transporte-logistica',
            'title' => 'Factura transporte e logística',
            'level' => 'avancado',
            'category' => 'factura',
            'style' => 'corporate',
            'description' => 'Para transportadoras e operadores logísticos com origem/destino e peso.',
            'features' => ['Rota', 'Peso / volume', 'Referência de guia'],
        ],
        [
            'slug' => 'factura-recorrente-mensal',
            'title' => 'Factura mensal recorrente',
            'level' => 'avancado',
            'category' => 'factura',
            'style' => 'modern',
            'description' => 'Subscrições, rendas e serviços mensais com período de faturação.',
            'features' => ['Período', 'Referência de contrato', 'Vencimento'],
        ],
        [
            'slug' => 'orcamento-detalhado',
            'title' => 'Orçamento detalhado profissional',
            'level' => 'avancado',
            'category' => 'orcamento',
            'style' => 'corporate',
            'description' => 'Orçamento completo com fases, condições comerciais e validade.',
            'features' => ['Fases do projecto', 'Condições', 'Aceitação do cliente'],
        ],
        [
            'slug' => 'factura-corporativa-angola',
            'title' => 'Factura corporativa Angola',
            'level' => 'avancado',
            'category' => 'factura',
            'style' => 'angola',
            'description' => 'Design sofisticado com identidade visual inspirada em Angola para empresas estabelecidas.',
            'features' => ['Cabeçalho premium', 'Cores Angola', 'Bloco bancário IBAN'],
        ],
        [
            'slug' => 'recibo-adiantamento',
            'title' => 'Recibo de adiantamento / sinal',
            'level' => 'avancado',
            'category' => 'recibo',
            'style' => 'classic',
            'description' => 'Recibo para sinais e adiantamentos sobre orçamentos ou proformas.',
            'features' => ['Referência ao orçamento', 'Saldo restante', 'Condições'],
        ],
    ],
];
